backend = "glx";

vsync = true;

# sombras
shadow = true;
shadow-radius = 12;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.35;

# transparencia
inactive-opacity = 0.92;
active-opacity = 1.0;
frame-opacity = 0.95;

# blur
blur-method = "dual_kawase";
blur-strength = 5;

# reglas
opacity-rule = [
  "50:class_g = 'kitty'",
];
